name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy Edge Functions
        run: |
          echo "🚀 Deploying Supabase Edge Functions..."
          supabase functions deploy make-server-e884809f
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_ID }}
      
      - name: Deployment Success
        if: success()
        run: |
          echo "✅ Supabase Functions deployed successfully!"
          echo "📍 URL: https://${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co/functions/v1/make-server-e884809f"
      
      - name: Deployment Failed
        if: failure()
        run: |
          echo "❌ Deployment failed. Check logs above for details."
          exit 1
